export async function getTonightsRec({vibeVector,answers,venues,savedVenueIds}){const topVenues=venues.slice(0,15).map(v=>({id:v.id,name:v.name,neighborhood:v.neighborhood,genres:v.music_genres,vibe_tags:v.vibe_tags.slice(0,3),music:v.music_score,energy:v.energy_score,dance:v.dance_score,crowd:v.crowd_desc}));const prompt=`You are a NYC nightlife recommendation engine. Pick the SINGLE best venue for this user tonight and give a punchy 1-sentence reason.

User vibe (out of 5): Music:${vibeVector.music?.toFixed(1)||3} Energy:${vibeVector.energy?.toFixed(1)||3} Dance:${vibeVector.dance?.toFixed(1)||3}
Seed artists: ${(vibeVector.seedArtists||[]).slice(0,5).join(', ')||'not set'}
Tonight: ${answers.q1} | ${answers.q2}${answers.currentSong?'\nListening to: "'+answers.currentSong+'"':''}

Venues:
${JSON.stringify(topVenues)}

Respond ONLY with JSON: {"venueId":"v1","reason":"specific reason","matchScore":87,"vibe":"2-3 words"}`;const anthropicKey=import.meta.env.VITE_ANTHROPIC_API_KEY;const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;try{let res,data;if(supabaseUrl){res=await fetch(supabaseUrl+'/functions/v1/get-rec',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});}else if(anthropicKey){res=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'Content-Type':'application/json','x-api-key':anthropicKey,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:300,messages:[{role:'user',content:prompt}]})});}else{throw new Error('No API');}data=await res.json();const text=supabaseUrl?data.text:(data.content?.[0]?.text||'');return JSON.parse(text.replace(/```json|```/g,'').trim());}catch{const scored=venues.map(v=>{let s=0;['music','energy','dance','demo'].forEach((k,i)=>{const d=['music_score','energy_score','dance_score','demo_score'][i];s+=1-Math.abs((vibeVector[k]||3)-v[d])/5;});return{...v,_s:s/4};}).sort((a,b)=>b._s-a._s);const best=scored[0];return{venueId:best.id,reason:'Based on your taste profile, '+best.name+' hits your sweet spot tonight.',matchScore:Math.round(best._s*100),vibe:best.vibe_tags[0]||'your vibe'};}}